/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package annual;

import java.io.File;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author talha
 */
public class AnnualLeaveFrame extends javax.swing.JFrame {

    /**
     * Creates new form AnnualLeaveFrame
     */
    public AnnualLeaveFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu2 = new javax.swing.JMenu();
        fileChooser = new javax.swing.JFileChooser();
        yillik = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        mazeret = new javax.swing.JRadioButton();
        evlilik = new javax.swing.JRadioButton();
        babalik = new javax.swing.JRadioButton();
        dogum = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        izinGun = new javax.swing.JComboBox<>();
        isim = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        rapor = new javax.swing.JRadioButton();
        sutizni = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("İzin İstek Formu");
        setLocation(new java.awt.Point(400, 200));

        buttonGroup1.add(yillik);
        yillik.setText("Yıllık İzin");
        yillik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yillikActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("İzin İstek Formu");

        buttonGroup1.add(mazeret);
        mazeret.setText("Mazeret İzni");
        mazeret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mazeretActionPerformed(evt);
            }
        });

        buttonGroup1.add(evlilik);
        evlilik.setText("Evlilik İzni");
        evlilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evlilikActionPerformed(evt);
            }
        });

        buttonGroup1.add(babalik);
        babalik.setText("Babalık İzni");
        babalik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                babalikActionPerformed(evt);
            }
        });

        buttonGroup1.add(dogum);
        dogum.setText("Doğum İzni");
        dogum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogumActionPerformed(evt);
            }
        });

        jLabel2.setText("İzin Başlangıç Tarihi");

        jXDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker1ActionPerformed(evt);
            }
        });

        jLabel3.setText("İzin Kullanılacak Toplam Gün");

        jLabel4.setText("İsminizi Seçiniz:");

        isim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isimActionPerformed(evt);
            }
        });
        Main nesne=new Main();
        try {
            nesne.getSheets();
        }
        catch(Exception e) {
            System.out.println("PERSONEL BILGILERI YUKLENIRKEN HATA MEYDANA GELDI.");
        }
        for(String person:nesne.sheetNames) {
            isim.addItem(person);
        }

        jButton1.setText("İznimi Kullanmak İstiyorum");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rapor);
        rapor.setText("Rapor");
        rapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raporActionPerformed(evt);
            }
        });

        buttonGroup1.add(sutizni);
        sutizni.setText("Süt İzni");
        sutizni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sutizniActionPerformed(evt);
            }
        });

        jMenu1.setText("Dosya");

        jMenuItem1.setText("Seç");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Çıkış");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rapor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yillik)
                                    .addComponent(dogum)
                                    .addComponent(babalik)
                                    .addComponent(evlilik)
                                    .addComponent(mazeret))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(isim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(izinGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1)
                                    .addComponent(jButton1)))
                            .addComponent(sutizni))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(yillik)
                .addGap(21, 21, 21)
                .addComponent(mazeret)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evlilik))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(izinGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(babalik))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dogum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(rapor)
                .addGap(21, 21, 21)
                .addComponent(sutizni)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
   
       
    
    
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void mazeretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mazeretActionPerformed
       izinGun.setModel(new DefaultComboBoxModel(new String[] { "1" }));
    }//GEN-LAST:event_mazeretActionPerformed

    private void yillikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yillikActionPerformed
        String[] dizi = new String[50];
    for (int i = 0; i < 50; i++) {
      dizi[i] = String.valueOf(i + 1);
    }
    izinGun.setModel(new DefaultComboBoxModel(dizi));
    }//GEN-LAST:event_yillikActionPerformed

    private void evlilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evlilikActionPerformed
    izinGun.setModel(new DefaultComboBoxModel(new String[] { "3" }));
    }//GEN-LAST:event_evlilikActionPerformed

    private void babalikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_babalikActionPerformed
    izinGun.setModel(new DefaultComboBoxModel(new String[] { "5" }));
    }//GEN-LAST:event_babalikActionPerformed

    private void dogumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogumActionPerformed
    izinGun.setModel(new DefaultComboBoxModel(new String[] { "112" }));
    }//GEN-LAST:event_dogumActionPerformed

    private void isimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isimActionPerformed

    private void raporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raporActionPerformed
        izinGun.setModel(new DefaultComboBoxModel(new String[] { "1","2","3","4","5" }));
    }//GEN-LAST:event_raporActionPerformed

    private void sutizniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sutizniActionPerformed
        izinGun.setModel(new DefaultComboBoxModel(new String[] { "0.5","1" }));
    }//GEN-LAST:event_sutizniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(fileChooser.getSelectedFile()==null) {
            JOptionPane.showMessageDialog(rootPane, "Dosya Seçmediniz!","UYARI",
                    JOptionPane.WARNING_MESSAGE);
        }
        else {
        String secilenizin=null;
       if(yillik.isSelected())
           secilenizin="yillik";
       else if(mazeret.isSelected())
           secilenizin="mazeret";
       else if(rapor.isSelected())
           secilenizin="rapor";
       else if(sutizni.isSelected())
           secilenizin="sutizni";
       else if(dogum.isSelected())
           secilenizin="dogumizni";
       else if(evlilik.isSelected())
           secilenizin="evlilik";
       else if(babalik.isSelected())
           secilenizin="babalik";
       
       
        if(secilenizin==null) {
            JOptionPane.showMessageDialog(rootPane, "İzin Türü Seçmediniz!","UYARI",
                    JOptionPane.WARNING_MESSAGE);
        }
        Annual annual=new Annual();
        try {
            double kalanIzin=annual.izin(jXDatePicker1.getDate(),izinGun.getSelectedItem().
                    toString(),secilenizin,isim.getSelectedItem().toString(),fileChooser.getSelectedFile().toString().replace("\\","\\\\"));
            if(kalanIzin==999) {
                            JOptionPane.showMessageDialog(rootPane, 
                                    "İZİN BAŞARILI BİR ŞEKİLDE EKLENDİ","BAŞARILI"
                                    ,JOptionPane.INFORMATION_MESSAGE);
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "İZİN BAŞARILI BİR ŞEKİLDE EKLENDİ"
                        + "\nKalan izin hakkınız: "+kalanIzin,"BAŞARILI",JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(),"HATA",JOptionPane.ERROR_MESSAGE);
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          int returnVal = fileChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
       
        
        
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnnualLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnnualLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnnualLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnnualLeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnnualLeaveFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton babalik;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dogum;
    private javax.swing.JRadioButton evlilik;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JComboBox<String> isim;
    private javax.swing.JComboBox<String> izinGun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JRadioButton mazeret;
    private javax.swing.JRadioButton rapor;
    private javax.swing.JRadioButton sutizni;
    private javax.swing.JRadioButton yillik;
    // End of variables declaration//GEN-END:variables
}
